# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-30 16:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('handle_coaches', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='coach',
            options={'ordering': ('date_joined',)},
        ),
        migrations.AddField(
            model_name='coach',
            name='cash',
            field=models.BooleanField(default=False, verbose_name='Cash'),
        ),
        migrations.AddField(
            model_name='coach',
            name='cr_ev',
            field=models.BooleanField(default=False, verbose_name='crEV'),
        ),
        migrations.AddField(
            model_name='coach',
            name='date_joined',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='coach',
            name='date_updated',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='coach',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='coach',
            name='english',
            field=models.BooleanField(default=False, verbose_name='Ingles'),
        ),
        migrations.AddField(
            model_name='coach',
            name='flopzilla',
            field=models.BooleanField(default=False, verbose_name='Floopzilla'),
        ),
        migrations.AddField(
            model_name='coach',
            name='french',
            field=models.BooleanField(default=False, verbose_name='Frances'),
        ),
        migrations.AddField(
            model_name='coach',
            name='german',
            field=models.BooleanField(default=False, verbose_name='Aleman'),
        ),
        migrations.AddField(
            model_name='coach',
            name='hold_them_manager',
            field=models.BooleanField(default=False, verbose_name="Hold'em Manager"),
        ),
        migrations.AddField(
            model_name='coach',
            name='hold_them_resources',
            field=models.BooleanField(default=False, verbose_name="Hold'em Resources"),
        ),
        migrations.AddField(
            model_name='coach',
            name='last_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='coach',
            name='mtt',
            field=models.BooleanField(default=False, verbose_name='MTT'),
        ),
        migrations.AddField(
            model_name='coach',
            name='mtt_normal',
            field=models.BooleanField(default=False, verbose_name='MTT Normal'),
        ),
        migrations.AddField(
            model_name='coach',
            name='mtt_sng',
            field=models.BooleanField(default=False, verbose_name='MTT SNG'),
        ),
        migrations.AddField(
            model_name='coach',
            name='nl_cap',
            field=models.BooleanField(default=False, verbose_name='NL CAP'),
        ),
        migrations.AddField(
            model_name='coach',
            name='nl_deep_stack',
            field=models.BooleanField(default=False, verbose_name='NL DeepStack'),
        ),
        migrations.AddField(
            model_name='coach',
            name='nl_heads_up',
            field=models.BooleanField(default=False, verbose_name='NL Heads Up'),
        ),
        migrations.AddField(
            model_name='coach',
            name='nl_multistack',
            field=models.BooleanField(default=False, verbose_name='NL MultiStack'),
        ),
        migrations.AddField(
            model_name='coach',
            name='plo_deepstack',
            field=models.BooleanField(default=False, verbose_name='PLO Deepstack'),
        ),
        migrations.AddField(
            model_name='coach',
            name='plo_hu',
            field=models.BooleanField(default=False, verbose_name='PLO HU'),
        ),
        migrations.AddField(
            model_name='coach',
            name='plo_multistack',
            field=models.BooleanField(default=False, verbose_name='PLO MultiStack'),
        ),
        migrations.AddField(
            model_name='coach',
            name='posolver_simple',
            field=models.BooleanField(default=False, verbose_name='Piosolver Simple Postflop'),
        ),
        migrations.AddField(
            model_name='coach',
            name='satelite',
            field=models.BooleanField(default=False, verbose_name='Satelite'),
        ),
        migrations.AddField(
            model_name='coach',
            name='sgn_normal',
            field=models.BooleanField(default=False, verbose_name='SNG Normal'),
        ),
        migrations.AddField(
            model_name='coach',
            name='skype',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='coach',
            name='sng',
            field=models.BooleanField(default=False, verbose_name='SNG'),
        ),
        migrations.AddField(
            model_name='coach',
            name='sng_hu',
            field=models.BooleanField(default=False, verbose_name='SNG HU'),
        ),
        migrations.AddField(
            model_name='coach',
            name='sng_hyperturbo',
            field=models.BooleanField(default=False, verbose_name='SNG Hyperturbo'),
        ),
        migrations.AddField(
            model_name='coach',
            name='sng_turbo',
            field=models.BooleanField(default=False, verbose_name='SNG Turbo'),
        ),
        migrations.AddField(
            model_name='coach',
            name='snowie',
            field=models.BooleanField(default=False, verbose_name='Snowie'),
        ),
        migrations.AddField(
            model_name='coach',
            name='software',
            field=models.BooleanField(default=False, verbose_name='Software'),
        ),
        migrations.AddField(
            model_name='coach',
            name='spanish',
            field=models.BooleanField(default=False, verbose_name='Espanol'),
        ),
        migrations.AddField(
            model_name='coach',
            name='spin_and_go',
            field=models.BooleanField(default=False, verbose_name='Spin and Go'),
        ),
        migrations.AlterField(
            model_name='coach',
            name='first_name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
