# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-30 19:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('handle_coaches', '0003_auto_20151230_1837'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coach',
            name='nl_cap_6max',
            field=models.BooleanField(default=False, verbose_name='NL CAP:6 Max'),
        ),
        migrations.AlterField(
            model_name='coach',
            name='nl_cap_FR',
            field=models.BooleanField(default=False, verbose_name='NL CAP:FR'),
        ),
        migrations.AlterField(
            model_name='coach',
            name='nl_deep_stack_6max',
            field=models.BooleanField(default=False, verbose_name='NL DeepStack:6 Max'),
        ),
        migrations.AlterField(
            model_name='coach',
            name='nl_deep_stack_FR',
            field=models.BooleanField(default=False, verbose_name='NL DeepStack:FR'),
        ),
        migrations.AlterField(
            model_name='coach',
            name='nl_heads_up_6max',
            field=models.BooleanField(default=False, verbose_name='NL Heads Up:6 Max'),
        ),
        migrations.AlterField(
            model_name='coach',
            name='nl_heads_up_FR',
            field=models.BooleanField(default=False, verbose_name='NL Heads Up:FR'),
        ),
        migrations.AlterField(
            model_name='coach',
            name='nl_multistack_6max',
            field=models.BooleanField(default=False, verbose_name='NL MultiStack:6 Max'),
        ),
        migrations.AlterField(
            model_name='coach',
            name='nl_multistack_FR',
            field=models.BooleanField(default=False, verbose_name='NL MultiStack:FR'),
        ),
        migrations.AlterField(
            model_name='coach',
            name='plo_deepstack_6max',
            field=models.BooleanField(default=False, verbose_name='PLO Deepstack:6 Max'),
        ),
        migrations.AlterField(
            model_name='coach',
            name='plo_deepstack_FR',
            field=models.BooleanField(default=False, verbose_name='PLO Deepstack:FR'),
        ),
        migrations.AlterField(
            model_name='coach',
            name='plo_hu_6max',
            field=models.BooleanField(default=False, verbose_name='PLO HU:6 Max'),
        ),
        migrations.AlterField(
            model_name='coach',
            name='plo_hu_FR',
            field=models.BooleanField(default=False, verbose_name='PLO HU:FR'),
        ),
        migrations.AlterField(
            model_name='coach',
            name='plo_multistack_6max',
            field=models.BooleanField(default=False, verbose_name='PLO MultiStack:6 Max'),
        ),
        migrations.AlterField(
            model_name='coach',
            name='plo_multistack_FR',
            field=models.BooleanField(default=False, verbose_name='PLO MultiStack:FR'),
        ),
    ]
