# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-30 19:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('handle_coaches', '0004_auto_20151230_1903'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coach',
            old_name='nl_heads_up_FR',
            new_name='nl_heads_up_cap',
        ),
        migrations.RemoveField(
            model_name='coach',
            name='nl_heads_up_6max',
        ),
        migrations.RemoveField(
            model_name='coach',
            name='plo_deepstack_FR',
        ),
        migrations.RemoveField(
            model_name='coach',
            name='plo_hu_6max',
        ),
        migrations.RemoveField(
            model_name='coach',
            name='plo_hu_FR',
        ),
        migrations.RemoveField(
            model_name='coach',
            name='plo_multistack_FR',
        ),
        migrations.RemoveField(
            model_name='coach',
            name='sgn_normal',
        ),
        migrations.RemoveField(
            model_name='coach',
            name='sng_hu',
        ),
        migrations.RemoveField(
            model_name='coach',
            name='sng_hyperturbo',
        ),
        migrations.RemoveField(
            model_name='coach',
            name='sng_turbo',
        ),
        migrations.RemoveField(
            model_name='coach',
            name='spin_and_go',
        ),
        migrations.AddField(
            model_name='coach',
            name='cash_other',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='coach',
            name='nl_heads_up_deep',
            field=models.BooleanField(default=False, verbose_name='NL Heads Up:FR'),
        ),
        migrations.AddField(
            model_name='coach',
            name='nl_heads_up_multistack',
            field=models.BooleanField(default=False, verbose_name='NL Heads Up:FR'),
        ),
        migrations.AddField(
            model_name='coach',
            name='plo_hu',
            field=models.BooleanField(default=False, verbose_name='PLO HU'),
        ),
        migrations.AddField(
            model_name='coach',
            name='sgn_normal_6max',
            field=models.BooleanField(default=False, verbose_name='SNG Normal:6max'),
        ),
        migrations.AddField(
            model_name='coach',
            name='sgn_normal_FR',
            field=models.BooleanField(default=False, verbose_name='SNG Normal:FR'),
        ),
        migrations.AddField(
            model_name='coach',
            name='sng_hu_hyperturbo',
            field=models.BooleanField(default=False, verbose_name='SNG HU:Hyperturbo'),
        ),
        migrations.AddField(
            model_name='coach',
            name='sng_hu_normal',
            field=models.BooleanField(default=False, verbose_name='SNG HU:Normal'),
        ),
        migrations.AddField(
            model_name='coach',
            name='sng_hu_turbo',
            field=models.BooleanField(default=False, verbose_name='SNG HU:Turbo'),
        ),
        migrations.AddField(
            model_name='coach',
            name='sng_hyperturbo_6max',
            field=models.BooleanField(default=False, verbose_name='SNG Hyperturbo:6max'),
        ),
        migrations.AddField(
            model_name='coach',
            name='sng_hyperturbo_FR',
            field=models.BooleanField(default=False, verbose_name='SNG Hyperturbo:FR'),
        ),
        migrations.AddField(
            model_name='coach',
            name='sng_turbo_6max',
            field=models.BooleanField(default=False, verbose_name='SNG Turbo:6max'),
        ),
        migrations.AddField(
            model_name='coach',
            name='sng_turbo_FR',
            field=models.BooleanField(default=False, verbose_name='SNG Turbo:FR'),
        ),
    ]
