# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-30 19:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('handle_coaches', '0005_auto_20151230_1937'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coach',
            old_name='sgn_normal_6max',
            new_name='sng_normal_6max',
        ),
        migrations.RenameField(
            model_name='coach',
            old_name='sgn_normal_FR',
            new_name='sng_normal_FR',
        ),
    ]
