# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-03 19:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('handle_coaches', '0007_coach_sng_spin_and_go'),
    ]

    operations = [
        migrations.AddField(
            model_name='coach',
            name='rating',
            field=models.IntegerField(default=5),
        ),
    ]
