# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-04 10:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('handle_coaches', '0008_coach_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coach',
            name='active',
            field=models.BooleanField(default=True, verbose_name='Publicar'),
        ),
    ]
