# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-04 10:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('handle_coaches', '0009_auto_20160104_1008'),
    ]

    operations = [
        migrations.AddField(
            model_name='coach',
            name='price',
            field=models.IntegerField(null=True),
        ),
    ]
