# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-04 15:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('handle_coaches', '0011_auto_20160104_1037'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coach',
            name='german',
        ),
        migrations.AddField(
            model_name='coach',
            name='russian',
            field=models.BooleanField(default=False, verbose_name='Ruso'),
        ),
    ]
