# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-03 20:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('handle_coaches', '0012_auto_20160103_2049'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coach',
            old_name='price',
            new_name='price_per_hour',
        ),
    ]
