# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-03 21:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('handle_coaches', '0014_coach_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coach',
            name='image',
            field=models.ImageField(default='static_files/None/no-img.jpg', upload_to='static_files/'),
        ),
    ]
