# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-04 16:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('handle_coaches', '0015_auto_20160103_2137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coach',
            name='image',
            field=models.ImageField(default='static_files/None/no-img.jpg', upload_to='profile_photos'),
        ),
    ]
