# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-04 22:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('handle_coaches', '0013_auto_20160104_2028'),
        ('handle_coaches', '0016_auto_20160104_1609'),
    ]

    operations = [
    ]
